### ISSUE TITLE
Could not run using python 3.5

### ISSUE THREAD

**Issue by uilianries** [kpn-iot/senml-python-library#1]
Hi!

First all, Thanks for providing this project as open source!

#### Summary
I'm running your examples and when I try to run examples/gateway.py I got the follow error:

```
Traceback (most recent call last):
  File "gateway.py", line 34, in <module>
    str_val.value = "test"
  File "/home/uilian/Development/playground/senml/venv/lib/python3.5/site-packages/kpn_senml-1.0.1-py3.5.egg/kpn_senml/senml_record.py", line 97, in value
  File "/home/uilian/Development/playground/senml/venv/lib/python3.5/site-packages/kpn_senml-1.0.1-py3.5.egg/kpn_senml/senml_record.py", line 72, in _check_value_type
NameError: name 'basestring' is not defined
```

#### Steps to Reproduce
- python3.5 -m venv venv
- source venv/bin/activate
- python setup.py install
- python examples/gateway.py

#### Environment
- OS: Linux Mint 18.3
- Arch: x86_64
- Python: 3.5.2

#### Expected Result
Run Gateway example without errors, including virtual sensor result on console

#### Actual Result
The example crashes

Regards!

**Comment by uilianries** [comment]
`basestring` was removed from python3:

https://docs.python.org/3.0/whatsnew/3.0.html#text-vs-data-instead-of-unicode-vs-8-bit

**Comment by jan-bogaerts** [comment]
Thansk for the feedback.  I' have a look at it tomorrow. This definitely sounds like a version conflict though.

**Comment by jan-bogaerts** [comment]
Hi,
Just did a check on the original project requirements and indeed the project is currently geared for python 2.7, not for python3 (was primarily for embedded environments, which often still use 2.7 only).  I'll update the docs for this.
There currently aren't any plans to migrate to python 3. If you would like to contribute to this project, I can accept your contributions.

**Comment by uilianries** [comment]
Nice! I appreciate your quick answer.

I'll communicate some coworkers to get some help here. Maybe they are able to submit a PR with python3 support.

Thanks!
